server:
  port: 9090

spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/kpi_dashboard
    username: anisdemni
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: kpi_dashboard
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: https://localhost:8080/auth/realms/kpi_dashboard
            user-name-attribute: preferred_username

keycloak:
  realm: kpi_dashboard
  auth-server-url: http://localhost:8080/
  ssl-required: external
  resource: kpi_dashboard
  public-client: true